version: '3.5'
services:
  socket-gateway-1:
    build:
      context: ./
      dockerfile: Dockerfile
    hostname: socket-gateway-1
    container_name: socket-gateway-1
    restart: always
    env_file:
      - .one.env
    volumes:
      - app:/var/www/html
    command:
      - yarn
      - start
  socket-gateway-2:
    build:
      context: ./
      dockerfile: Dockerfile
    hostname: socket-gateway-2
    container_name: socket-gateway-2
    restart: always
    env_file:
      - .two.env
    volumes:
      - app:/var/www/html
    command:
      - yarn
      - start
  socket-gateway-proxy:
    image: nginx:alpine
    hostname: socket-gateway-proxy
    container_name: socket-gateway-proxy
    restart: unless-stopped
    depends_on:
      - socket-gateway-1
      - socket-gateway-2
    ports:
      - 8001:8001
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf

volumes:
  app:

networks:
  default:
    name: 'simple-trader'
    external: true